# Generated by Django 4.0.5 on 2022-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aphis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('date', models.DateTimeField()),
                ('length_of_body', models.FloatField()),
            ],
        ),
    ]
